#!/bin/bash 
#SBATCH --partition=short-serial 
#SBATCH --job-name=280K_run 
#SBATCH -o ../log/run_280K.out 
#SBATCH -e ../log/%j.err
#SBATCH --time=24:00:00

conda activate ecsbump

python /gws/nopw/j04/aopp/andreww/side_projects/ECS_bump/run_pyrads.py --temp=281
